name: NathanNeighbour
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6203201510943472
title: Nathan Neighbour
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#363636'
    - '#ffffff'
    - '#bfbfbf'
    - '#777777'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
